// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xX31PjNhD+VzTbPjpxEgLX+o2DFDLlCAO0LwwPwt4kutqSK8nhMkz+947k37ZS0g5w",
	"L/cCGf3Y3W+/b1frFwhFkgqOXCsIXkCFa0yo/TmTUkjzI5UiRakZ2mUslyNUoWSpZoJDkJ8mCSpFVwge",
	"4DeapDFCAHO+oTGLiMS/M1SapFTSBDVKRQbkT7NFjQ3yG2UxRuCB3qbmntKS8RXsygW3R7vXdLfWOlWB",
	"7xcrw1Akvo1Z+U80GhRRgAdLIROqIYBMsoHEJUrkIfb97zwwl5jECIKHAn9x6rE6LZ6+YqhNtJdIY73u",
	"Jy6l+WobxRnlgrOQxsTsE7Ekeo1EohKZDDvIcsMmHBoteLyFQMsMHQlTmupM9Z3loZFiu29760TfRujB",
	"twHFdFCFaKDFmaRxZcaYVoyvYtTGbR6kWchiKmsgxvbChqb62aJxLJ4x+oJ6LSIHlNN8nyTFgQaYB7iY",
	"3YMHN4s7++8P8/d8djW7n4EHi5v7+eL6zlDHNCbW9B7FAZWSbh052HlwI8WGRSjvUG5YkYV2nfAoFYxr",
	"h3CLnZJsVZhwEMlp4lD+NU3w1csd2VpLXh3V4+u8Gt76SK+Y0n20RRj2d5XWnyUuIYCf/LrH+EWD8TtW",
	"b1Glgit0Jr+Jo3L0+DopldFcT4slBA//KSrYeV2gLOrzMT/vs1GX1nhyhNPjk08D/OXXp8F4Eh0N6PT4",
	"ZDCdnJyMp+NP09Fo1GpHGYtepZNFjgQ87jy4bZZlu/8U2N6BIxNb7vbe2arNqqu18SwxYDYJeBAKrinj",
	"KBvAGh3NhtS3fGfXHbY7qemkrxVuZf3wmiiz7C6G8vjhma5Ye03+tek+/eYs40thnNlshia2nddJWckq",
	"KWglpzdz8CBmIRa1kncdOE1puEYyGRp5ZjJuPK7Pz89DareHQq784q7yr+Zns+u72WAyHA3XOoktHqZt",
	"HVR+VcvvBqXKA9uMaZyu6dhcEilymjII4Gg4sgGY59Hm0V9XD+wK9d5HLlxj+BdZCknOz76QPc4Na3b6",
	"mEcQwAXqy/qNzcVuXU5GozKpmHd0mqYxC+1V/6syfl8aGv03qi/Lx69HzOJ3S7fKkoTKbQeJ3fJbynKi",
	"N4okNI5JfbQL0xy5bey+G9RWlZj4m6a2NIn/tyln7jyYvmHw+fjrcPWZVrOs8Xn8ET7nXKPkNLbyRUmw",
	"ONhUywV2ibd1VM1XnYTlG7ZA9kulOPUhailHwUMqwx19u0T8l2aX3+2tGJu3ygp52pbfFL3mcFs/L/VH",
	"jJ0pmDFkB/xyZus+MXUTL8bhKicHv4K7xw+o1Teq0x81ur9G+1rbeZAK5dDmLa6Y0igJJRyfSTnCtXTv",
	"lmt5s3jky/fvu0rX8vFZRNs3I6M3r7fnpWJa6xTN+L3c1wPyD/E7xH+4mK2D3FIu0nz69M0nzj8BAAD/",
	"//7KWJuyEgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
