// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package server

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	externalRef0 "github.com/dcm-project/dcm-placement-api/api/v1alpha1/provider"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CatalogItemResourceType.
const (
	CatalogItemResourceTypeContainer CatalogItemResourceType = "container"
	CatalogItemResourceTypeVm        CatalogItemResourceType = "vm"
)

// Defines values for CatalogItemResponseResourceType.
const (
	CatalogItemResponseResourceTypeContainer CatalogItemResponseResourceType = "container"
	CatalogItemResponseResourceTypeVm        CatalogItemResponseResourceType = "vm"
)

// CatalogInstance defines model for CatalogInstance.
type CatalogInstance struct {
	CatalogItem CatalogItem `json:"catalogItem"`

	// Name Name of the instance
	Name string `json:"name"`
}

// CatalogInstanceList defines model for CatalogInstanceList.
type CatalogInstanceList struct {
	Instances []CatalogInstance `json:"instances"`
}

// CatalogInstanceResponse defines model for CatalogInstanceResponse.
type CatalogInstanceResponse struct {
	CatalogItem CatalogItem `json:"catalogItem"`

	// Id ID of the instance
	Id *openapi_types.UUID `json:"id,omitempty"`

	// Name Name of the instance
	Name     string                                `json:"name"`
	Provider *externalRef0.ProviderServiceResponse `json:"provider,omitempty"`

	// Status Status of the instance
	Status *string `json:"status,omitempty"`
}

// CatalogInstanceResponseList defines model for CatalogInstanceResponseList.
type CatalogInstanceResponseList struct {
	Instances []CatalogInstanceResponse `json:"instances"`
}

// CatalogItem defines model for CatalogItem.
type CatalogItem struct {
	// Name Name of the instance
	Name string `json:"name"`

	// Parameters Content of the catalog item
	Parameters map[string]interface{} `json:"parameters"`

	// ResourceType Resource type of the catalog item
	ResourceType CatalogItemResourceType `json:"resourceType"`
}

// CatalogItemResourceType Resource type of the catalog item
type CatalogItemResourceType string

// CatalogItemList defines model for CatalogItemList.
type CatalogItemList struct {
	CatalogItems []CatalogItem `json:"catalogItems"`
}

// CatalogItemResponse defines model for CatalogItemResponse.
type CatalogItemResponse struct {
	// Id ID of the instance
	Id openapi_types.UUID `json:"id"`

	// Name Name of the instance
	Name string `json:"name"`

	// Parameters Content of the catalog item
	Parameters map[string]interface{} `json:"parameters"`

	// ResourceType Resource type of the catalog item
	ResourceType CatalogItemResponseResourceType `json:"resourceType"`
}

// CatalogItemResponseResourceType Resource type of the catalog item
type CatalogItemResponseResourceType string

// Error defines model for Error.
type Error struct {
	// Error Error message
	Error string `json:"error"`

	// Type Error type
	Type string `json:"type"`
}

// Health defines model for Health.
type Health struct {
	// Path Canonical path of the resource
	Path *string `json:"path,omitempty"`

	// Status Health status
	Status *string `json:"status,omitempty"`
}

// Options defines model for Options.
type Options struct {
	// AllowedMethods Allowed methods
	AllowedMethods *[]string `json:"allowedMethods,omitempty"`
}

// CreateCatalogInstanceJSONRequestBody defines body for CreateCatalogInstance for application/json ContentType.
type CreateCatalogInstanceJSONRequestBody = CatalogInstance

// CreateCatalogItemJSONRequestBody defines body for CreateCatalogItem for application/json ContentType.
type CreateCatalogItemJSONRequestBody = CatalogItem

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get all catalog instances
	// (GET /cataloginstances)
	ListCatalogInstances(w http.ResponseWriter, r *http.Request)
	// Create an catalog instance
	// (POST /cataloginstances)
	CreateCatalogInstance(w http.ResponseWriter, r *http.Request)
	// Delete an catalog instance
	// (DELETE /cataloginstances/{id})
	DeleteCatalogInstance(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Get all catalog items
	// (GET /catalogitems)
	ListCatalogItems(w http.ResponseWriter, r *http.Request)
	// Options for catalog items
	// (OPTIONS /catalogitems)
	OptionsCatalogItems(w http.ResponseWriter, r *http.Request)
	// Create an catalog item
	// (POST /catalogitems)
	CreateCatalogItem(w http.ResponseWriter, r *http.Request)
	// Delete an catalog item
	// (DELETE /catalogitems/{id})
	DeleteCatalogItem(w http.ResponseWriter, r *http.Request, id string)
	// Health check
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Get all catalog instances
// (GET /cataloginstances)
func (_ Unimplemented) ListCatalogInstances(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create an catalog instance
// (POST /cataloginstances)
func (_ Unimplemented) CreateCatalogInstance(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete an catalog instance
// (DELETE /cataloginstances/{id})
func (_ Unimplemented) DeleteCatalogInstance(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get all catalog items
// (GET /catalogitems)
func (_ Unimplemented) ListCatalogItems(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Options for catalog items
// (OPTIONS /catalogitems)
func (_ Unimplemented) OptionsCatalogItems(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create an catalog item
// (POST /catalogitems)
func (_ Unimplemented) CreateCatalogItem(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete an catalog item
// (DELETE /catalogitems/{id})
func (_ Unimplemented) DeleteCatalogItem(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Health check
// (GET /health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListCatalogInstances operation middleware
func (siw *ServerInterfaceWrapper) ListCatalogInstances(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCatalogInstances(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// CreateCatalogInstance operation middleware
func (siw *ServerInterfaceWrapper) CreateCatalogInstance(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCatalogInstance(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// DeleteCatalogInstance operation middleware
func (siw *ServerInterfaceWrapper) DeleteCatalogInstance(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteCatalogInstance(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// ListCatalogItems operation middleware
func (siw *ServerInterfaceWrapper) ListCatalogItems(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCatalogItems(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// OptionsCatalogItems operation middleware
func (siw *ServerInterfaceWrapper) OptionsCatalogItems(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.OptionsCatalogItems(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// CreateCatalogItem operation middleware
func (siw *ServerInterfaceWrapper) CreateCatalogItem(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCatalogItem(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// DeleteCatalogItem operation middleware
func (siw *ServerInterfaceWrapper) DeleteCatalogItem(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteCatalogItem(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/cataloginstances", wrapper.ListCatalogInstances)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/cataloginstances", wrapper.CreateCatalogInstance)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/cataloginstances/{id}", wrapper.DeleteCatalogInstance)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/catalogitems", wrapper.ListCatalogItems)
	})
	r.Group(func(r chi.Router) {
		r.Options(options.BaseURL+"/catalogitems", wrapper.OptionsCatalogItems)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/catalogitems", wrapper.CreateCatalogItem)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/catalogitems/{id}", wrapper.DeleteCatalogItem)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.GetHealth)
	})

	return r
}

type ListCatalogInstancesRequestObject struct {
}

type ListCatalogInstancesResponseObject interface {
	VisitListCatalogInstancesResponse(w http.ResponseWriter) error
}

type ListCatalogInstances200JSONResponse CatalogInstanceResponseList

func (response ListCatalogInstances200JSONResponse) VisitListCatalogInstancesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListCatalogInstances400JSONResponse Error

func (response ListCatalogInstances400JSONResponse) VisitListCatalogInstancesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ListCatalogInstances500JSONResponse Error

func (response ListCatalogInstances500JSONResponse) VisitListCatalogInstancesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateCatalogInstanceRequestObject struct {
	Body *CreateCatalogInstanceJSONRequestBody
}

type CreateCatalogInstanceResponseObject interface {
	VisitCreateCatalogInstanceResponse(w http.ResponseWriter) error
}

type CreateCatalogInstance201JSONResponse CatalogInstanceResponse

func (response CreateCatalogInstance201JSONResponse) VisitCreateCatalogInstanceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateCatalogInstance400JSONResponse Error

func (response CreateCatalogInstance400JSONResponse) VisitCreateCatalogInstanceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateCatalogInstance500JSONResponse Error

func (response CreateCatalogInstance500JSONResponse) VisitCreateCatalogInstanceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteCatalogInstanceRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type DeleteCatalogInstanceResponseObject interface {
	VisitDeleteCatalogInstanceResponse(w http.ResponseWriter) error
}

type DeleteCatalogInstance204JSONResponse CatalogInstanceResponse

func (response DeleteCatalogInstance204JSONResponse) VisitDeleteCatalogInstanceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(204)

	return json.NewEncoder(w).Encode(response)
}

type DeleteCatalogInstance400JSONResponse Error

func (response DeleteCatalogInstance400JSONResponse) VisitDeleteCatalogInstanceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type DeleteCatalogInstance500JSONResponse Error

func (response DeleteCatalogInstance500JSONResponse) VisitDeleteCatalogInstanceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ListCatalogItemsRequestObject struct {
}

type ListCatalogItemsResponseObject interface {
	VisitListCatalogItemsResponse(w http.ResponseWriter) error
}

type ListCatalogItems200JSONResponse CatalogItemList

func (response ListCatalogItems200JSONResponse) VisitListCatalogItemsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListCatalogItems400JSONResponse Error

func (response ListCatalogItems400JSONResponse) VisitListCatalogItemsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ListCatalogItems500JSONResponse Error

func (response ListCatalogItems500JSONResponse) VisitListCatalogItemsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type OptionsCatalogItemsRequestObject struct {
}

type OptionsCatalogItemsResponseObject interface {
	VisitOptionsCatalogItemsResponse(w http.ResponseWriter) error
}

type OptionsCatalogItems200JSONResponse Options

func (response OptionsCatalogItems200JSONResponse) VisitOptionsCatalogItemsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CreateCatalogItemRequestObject struct {
	Body *CreateCatalogItemJSONRequestBody
}

type CreateCatalogItemResponseObject interface {
	VisitCreateCatalogItemResponse(w http.ResponseWriter) error
}

type CreateCatalogItem201JSONResponse CatalogItemResponse

func (response CreateCatalogItem201JSONResponse) VisitCreateCatalogItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateCatalogItem400JSONResponse Error

func (response CreateCatalogItem400JSONResponse) VisitCreateCatalogItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateCatalogItem500JSONResponse Error

func (response CreateCatalogItem500JSONResponse) VisitCreateCatalogItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteCatalogItemRequestObject struct {
	Id string `json:"id"`
}

type DeleteCatalogItemResponseObject interface {
	VisitDeleteCatalogItemResponse(w http.ResponseWriter) error
}

type DeleteCatalogItem204JSONResponse CatalogItemResponse

func (response DeleteCatalogItem204JSONResponse) VisitDeleteCatalogItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(204)

	return json.NewEncoder(w).Encode(response)
}

type DeleteCatalogItem400JSONResponse Error

func (response DeleteCatalogItem400JSONResponse) VisitDeleteCatalogItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type DeleteCatalogItem500JSONResponse Error

func (response DeleteCatalogItem500JSONResponse) VisitDeleteCatalogItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse Health

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Get all catalog instances
	// (GET /cataloginstances)
	ListCatalogInstances(ctx context.Context, request ListCatalogInstancesRequestObject) (ListCatalogInstancesResponseObject, error)
	// Create an catalog instance
	// (POST /cataloginstances)
	CreateCatalogInstance(ctx context.Context, request CreateCatalogInstanceRequestObject) (CreateCatalogInstanceResponseObject, error)
	// Delete an catalog instance
	// (DELETE /cataloginstances/{id})
	DeleteCatalogInstance(ctx context.Context, request DeleteCatalogInstanceRequestObject) (DeleteCatalogInstanceResponseObject, error)
	// Get all catalog items
	// (GET /catalogitems)
	ListCatalogItems(ctx context.Context, request ListCatalogItemsRequestObject) (ListCatalogItemsResponseObject, error)
	// Options for catalog items
	// (OPTIONS /catalogitems)
	OptionsCatalogItems(ctx context.Context, request OptionsCatalogItemsRequestObject) (OptionsCatalogItemsResponseObject, error)
	// Create an catalog item
	// (POST /catalogitems)
	CreateCatalogItem(ctx context.Context, request CreateCatalogItemRequestObject) (CreateCatalogItemResponseObject, error)
	// Delete an catalog item
	// (DELETE /catalogitems/{id})
	DeleteCatalogItem(ctx context.Context, request DeleteCatalogItemRequestObject) (DeleteCatalogItemResponseObject, error)
	// Health check
	// (GET /health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListCatalogInstances operation middleware
func (sh *strictHandler) ListCatalogInstances(w http.ResponseWriter, r *http.Request) {
	var request ListCatalogInstancesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListCatalogInstances(ctx, request.(ListCatalogInstancesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListCatalogInstances")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListCatalogInstancesResponseObject); ok {
		if err := validResponse.VisitListCatalogInstancesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateCatalogInstance operation middleware
func (sh *strictHandler) CreateCatalogInstance(w http.ResponseWriter, r *http.Request) {
	var request CreateCatalogInstanceRequestObject

	var body CreateCatalogInstanceJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateCatalogInstance(ctx, request.(CreateCatalogInstanceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateCatalogInstance")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateCatalogInstanceResponseObject); ok {
		if err := validResponse.VisitCreateCatalogInstanceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteCatalogInstance operation middleware
func (sh *strictHandler) DeleteCatalogInstance(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request DeleteCatalogInstanceRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteCatalogInstance(ctx, request.(DeleteCatalogInstanceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteCatalogInstance")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteCatalogInstanceResponseObject); ok {
		if err := validResponse.VisitDeleteCatalogInstanceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListCatalogItems operation middleware
func (sh *strictHandler) ListCatalogItems(w http.ResponseWriter, r *http.Request) {
	var request ListCatalogItemsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListCatalogItems(ctx, request.(ListCatalogItemsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListCatalogItems")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListCatalogItemsResponseObject); ok {
		if err := validResponse.VisitListCatalogItemsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// OptionsCatalogItems operation middleware
func (sh *strictHandler) OptionsCatalogItems(w http.ResponseWriter, r *http.Request) {
	var request OptionsCatalogItemsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.OptionsCatalogItems(ctx, request.(OptionsCatalogItemsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "OptionsCatalogItems")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(OptionsCatalogItemsResponseObject); ok {
		if err := validResponse.VisitOptionsCatalogItemsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateCatalogItem operation middleware
func (sh *strictHandler) CreateCatalogItem(w http.ResponseWriter, r *http.Request) {
	var request CreateCatalogItemRequestObject

	var body CreateCatalogItemJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateCatalogItem(ctx, request.(CreateCatalogItemRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateCatalogItem")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateCatalogItemResponseObject); ok {
		if err := validResponse.VisitCreateCatalogItemResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteCatalogItem operation middleware
func (sh *strictHandler) DeleteCatalogItem(w http.ResponseWriter, r *http.Request, id string) {
	var request DeleteCatalogItemRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteCatalogItem(ctx, request.(DeleteCatalogItemRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteCatalogItem")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteCatalogItemResponseObject); ok {
		if err := validResponse.VisitDeleteCatalogItemResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
