openapi: 3.0.0
info:
  contact: {}
  description: DCM API
  title: DCP API
  version: v1alpha1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: /

paths:
  /health:
    get:
      summary: Health check
      operationId: GetHealth
      description: Health check for DCM API
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Health'
  /catalogitems:
    options:
      summary: Options for catalog items
      operationId: optionsCatalogItems
      description: Options for catalog items
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Options'
    post:
      summary: Create an catalog item
      operationId: createCatalogItem
      description: Create an catalog item
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CatalogItem'
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CatalogItemResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    get:
      summary: Get all catalog items
      operationId: listCatalogItems
      description: List all catalog items
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CatalogItemList'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /catalogitems/{id}:
    delete:
      summary: Delete an catalog item
      operationId: deleteCatalogItem
      description: Delete catalog item based on unique ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No Content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CatalogItemResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /cataloginstances:
    post:
      summary: Create an catalog instance
      operationId: createCatalogInstance
      description: Create an catalog instance
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CatalogInstance'
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CatalogInstanceResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    get:
      summary: Get all catalog instances
      operationId: listCatalogInstances
      description: List all catalog instances
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CatalogInstanceResponseList'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /cataloginstances/{id}:
    delete:
      summary: Delete an catalog instance
      operationId: deleteCatalogInstance
      description: Delete catalog item based on unique ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: No Content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CatalogInstanceResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Options:
      type: object
      properties:
        allowedMethods:
          type: array
          items:
            type: string
          description: Allowed methods
          example: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    CatalogItem:
      type: object
      x-aep-resource: true
      required:
        - name
        - resourceType
        - parameters
      properties:
        name:
          type: string
          description: Name of the instance
        resourceType:
          type: string
          description: Resource type of the catalog item
          enum:
            - vm
            - container
        parameters:
          type: object
          description: Content of the catalog item
    CatalogItemResponse:
       allOf:
        - $ref: '#/components/schemas/CatalogItem'
        - type: object
          required:
            - id
          properties:
            id:
              type: string
              description: ID of the instance
              example: "123e4567-e89b-12d3-a456-426614174000"
              format: uuid
    CatalogItemList:
      type: object
      required:
        - catalogItems
      properties:
        catalogItems:
          type: array
          items:
            $ref: '#/components/schemas/CatalogItem'
    CatalogInstance:
      type: object
      required:
        - name
        - catalogItem
      properties:
        name:
          type: string
          description: Name of the instance
          example: "app-server-01"
        catalogItem:
          $ref: '#/components/schemas/CatalogItem'
    CatalogInstanceResponse:
      allOf:
        - $ref: '#/components/schemas/CatalogInstance'
        - type: object
          properties:
            id:
              type: string
              description: ID of the instance
              example: "123e4567-e89b-12d3-a456-426614174000"
              format: uuid
            status:
              type: string
              description: Status of the instance
              example: "placed"
            provider:
              $ref: './provider/openapi.yaml#/components/schemas/ProviderServiceResponse'
              description: Provider of the instance
    CatalogInstanceList:
      type: object
      required:
        - instances
      properties:
        instances:
          type: array
          items:
            $ref: '#/components/schemas/CatalogInstance'
    CatalogInstanceResponseList:
      type: object
      required:
        - instances
      properties:
        instances:
          type: array
          items:
            $ref: '#/components/schemas/CatalogInstanceResponse'
    Error:
      required:
        - error
        - type
      type: object
      properties:
        type:
          type: string
          format: uri-reference
          description: Error type
          example: "https://example.com/errors/bad-request"
        error:
          type: string
          description: Error message
          example: "Invalid request parameters - Validation Failed"
    Health:
      type: object
      x-aep-resource:
        singular: health
        plural: healths
        singleton: true
      properties:
        status:
          type: string
          description: Health status
          example: "healthy"
        path:
          type: string
          description: Canonical path of the resource
          example: "health"
          readOnly: true
