// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1alpha1

import (
	externalRef0 "github.com/dcm-project/dcm-placement-api/api/v1alpha1/provider"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CatalogItemResourceType.
const (
	CatalogItemResourceTypeContainer CatalogItemResourceType = "container"
	CatalogItemResourceTypeVm        CatalogItemResourceType = "vm"
)

// Defines values for CatalogItemResponseResourceType.
const (
	CatalogItemResponseResourceTypeContainer CatalogItemResponseResourceType = "container"
	CatalogItemResponseResourceTypeVm        CatalogItemResponseResourceType = "vm"
)

// CatalogInstance defines model for CatalogInstance.
type CatalogInstance struct {
	CatalogItem CatalogItem `json:"catalogItem"`

	// Name Name of the instance
	Name string `json:"name"`
}

// CatalogInstanceList defines model for CatalogInstanceList.
type CatalogInstanceList struct {
	Instances []CatalogInstance `json:"instances"`
}

// CatalogInstanceResponse defines model for CatalogInstanceResponse.
type CatalogInstanceResponse struct {
	CatalogItem CatalogItem `json:"catalogItem"`

	// Id ID of the instance
	Id *openapi_types.UUID `json:"id,omitempty"`

	// Name Name of the instance
	Name     string                                `json:"name"`
	Provider *externalRef0.ProviderServiceResponse `json:"provider,omitempty"`

	// Status Status of the instance
	Status *string `json:"status,omitempty"`
}

// CatalogInstanceResponseList defines model for CatalogInstanceResponseList.
type CatalogInstanceResponseList struct {
	Instances []CatalogInstanceResponse `json:"instances"`
}

// CatalogItem defines model for CatalogItem.
type CatalogItem struct {
	// Name Name of the instance
	Name string `json:"name"`

	// Parameters Content of the catalog item
	Parameters map[string]interface{} `json:"parameters"`

	// ResourceType Resource type of the catalog item
	ResourceType CatalogItemResourceType `json:"resourceType"`
}

// CatalogItemResourceType Resource type of the catalog item
type CatalogItemResourceType string

// CatalogItemList defines model for CatalogItemList.
type CatalogItemList struct {
	CatalogItems []CatalogItem `json:"catalogItems"`
}

// CatalogItemResponse defines model for CatalogItemResponse.
type CatalogItemResponse struct {
	// Id ID of the instance
	Id openapi_types.UUID `json:"id"`

	// Name Name of the instance
	Name string `json:"name"`

	// Parameters Content of the catalog item
	Parameters map[string]interface{} `json:"parameters"`

	// ResourceType Resource type of the catalog item
	ResourceType CatalogItemResponseResourceType `json:"resourceType"`
}

// CatalogItemResponseResourceType Resource type of the catalog item
type CatalogItemResponseResourceType string

// Error defines model for Error.
type Error struct {
	// Error Error message
	Error string `json:"error"`

	// Type Error type
	Type string `json:"type"`
}

// Health defines model for Health.
type Health struct {
	// Path Canonical path of the resource
	Path *string `json:"path,omitempty"`

	// Status Health status
	Status *string `json:"status,omitempty"`
}

// Options defines model for Options.
type Options struct {
	// AllowedMethods Allowed methods
	AllowedMethods *[]string `json:"allowedMethods,omitempty"`
}

// CreateCatalogInstanceJSONRequestBody defines body for CreateCatalogInstance for application/json ContentType.
type CreateCatalogInstanceJSONRequestBody = CatalogInstance

// CreateCatalogItemJSONRequestBody defines body for CreateCatalogItem for application/json ContentType.
type CreateCatalogItemJSONRequestBody = CatalogItem
