// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package server

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ResourceResourceType.
const (
	ResourceResourceTypeContainer ResourceResourceType = "container"
	ResourceResourceTypeVm        ResourceResourceType = "vm"
)

// Defines values for GetResourceParamsResourceType.
const (
	GetResourceParamsResourceTypeContainer GetResourceParamsResourceType = "container"
	GetResourceParamsResourceTypeVm        GetResourceParamsResourceType = "vm"
)

// Defines values for RegisterServiceProviderParamsResourceType.
const (
	Container RegisterServiceProviderParamsResourceType = "container"
	Vm        RegisterServiceProviderParamsResourceType = "vm"
)

// Error defines model for Error.
type Error struct {
	// Error Error message
	Error string `json:"error"`

	// Type Error type
	Type string `json:"type"`
}

// Health defines model for Health.
type Health struct {
	// Path Canonical path of the resource
	Path *string `json:"path,omitempty"`

	// Status Health status
	Status *string `json:"status,omitempty"`
}

// Options defines model for Options.
type Options struct {
	// AllowedMethods Allowed methods
	AllowedMethods *[]string `json:"allowedMethods,omitempty"`
}

// ProviderService defines model for ProviderService.
type ProviderService struct {
	// Endpoint Endpoint of the service
	Endpoint string `json:"endpoint"`

	// Name Name of the service
	Name string `json:"name"`
}

// ProviderServiceList defines model for ProviderServiceList.
type ProviderServiceList struct {
	Services []ProviderServiceResponse `json:"services"`
}

// ProviderServiceResponse defines model for ProviderServiceResponse.
type ProviderServiceResponse struct {
	// Endpoint Endpoint of the service
	Endpoint string `json:"endpoint"`

	// Id ID of the service
	Id openapi_types.UUID `json:"id"`

	// Name Name of the service
	Name string `json:"name"`
}

// Resource defines model for Resource.
type Resource struct {
	Providers *[]ProviderServiceResponse `json:"providers,omitempty"`

	// ResourceType Type of the resource
	ResourceType ResourceResourceType `json:"resourceType"`

	// Schema Schema of the resource
	Schema map[string]interface{} `json:"schema"`
}

// ResourceResourceType Type of the resource
type ResourceResourceType string

// ResourceList defines model for ResourceList.
type ResourceList struct {
	Resources []Resource `json:"resources"`
}

// GetResourceParamsResourceType defines parameters for GetResource.
type GetResourceParamsResourceType string

// RegisterServiceProviderParamsResourceType defines parameters for RegisterServiceProvider.
type RegisterServiceProviderParamsResourceType string

// RegisterServiceProviderJSONRequestBody defines body for RegisterServiceProvider for application/json ContentType.
type RegisterServiceProviderJSONRequestBody = ProviderService

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Health check
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// Get all resources
	// (GET /resources)
	ListResources(w http.ResponseWriter, r *http.Request)
	// Options for resources
	// (OPTIONS /resources)
	OptionsResources(w http.ResponseWriter, r *http.Request)
	// Get a resource by type
	// (GET /resources/{resourceType})
	GetResource(w http.ResponseWriter, r *http.Request, resourceType GetResourceParamsResourceType)
	// Register a new provider for resource type
	// (POST /resources/{resourceType})
	RegisterServiceProvider(w http.ResponseWriter, r *http.Request, resourceType RegisterServiceProviderParamsResourceType)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Health check
// (GET /health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get all resources
// (GET /resources)
func (_ Unimplemented) ListResources(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Options for resources
// (OPTIONS /resources)
func (_ Unimplemented) OptionsResources(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a resource by type
// (GET /resources/{resourceType})
func (_ Unimplemented) GetResource(w http.ResponseWriter, r *http.Request, resourceType GetResourceParamsResourceType) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Register a new provider for resource type
// (POST /resources/{resourceType})
func (_ Unimplemented) RegisterServiceProvider(w http.ResponseWriter, r *http.Request, resourceType RegisterServiceProviderParamsResourceType) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// ListResources operation middleware
func (siw *ServerInterfaceWrapper) ListResources(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListResources(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// OptionsResources operation middleware
func (siw *ServerInterfaceWrapper) OptionsResources(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.OptionsResources(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetResource operation middleware
func (siw *ServerInterfaceWrapper) GetResource(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "resourceType" -------------
	var resourceType GetResourceParamsResourceType

	err = runtime.BindStyledParameterWithOptions("simple", "resourceType", chi.URLParam(r, "resourceType"), &resourceType, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "resourceType", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetResource(w, r, resourceType)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// RegisterServiceProvider operation middleware
func (siw *ServerInterfaceWrapper) RegisterServiceProvider(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "resourceType" -------------
	var resourceType RegisterServiceProviderParamsResourceType

	err = runtime.BindStyledParameterWithOptions("simple", "resourceType", chi.URLParam(r, "resourceType"), &resourceType, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "resourceType", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterServiceProvider(w, r, resourceType)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/resources", wrapper.ListResources)
	})
	r.Group(func(r chi.Router) {
		r.Options(options.BaseURL+"/resources", wrapper.OptionsResources)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/resources/{resourceType}", wrapper.GetResource)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/resources/{resourceType}", wrapper.RegisterServiceProvider)
	})

	return r
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse Health

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListResourcesRequestObject struct {
}

type ListResourcesResponseObject interface {
	VisitListResourcesResponse(w http.ResponseWriter) error
}

type ListResources200JSONResponse ResourceList

func (response ListResources200JSONResponse) VisitListResourcesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListResources200ApplicationyamlResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response ListResources200ApplicationyamlResponse) VisitListResourcesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/yaml")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type ListResources400JSONResponse Error

func (response ListResources400JSONResponse) VisitListResourcesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ListResources500JSONResponse Error

func (response ListResources500JSONResponse) VisitListResourcesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type OptionsResourcesRequestObject struct {
}

type OptionsResourcesResponseObject interface {
	VisitOptionsResourcesResponse(w http.ResponseWriter) error
}

type OptionsResources200JSONResponse Options

func (response OptionsResources200JSONResponse) VisitOptionsResourcesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetResourceRequestObject struct {
	ResourceType GetResourceParamsResourceType `json:"resourceType"`
}

type GetResourceResponseObject interface {
	VisitGetResourceResponse(w http.ResponseWriter) error
}

type GetResource200JSONResponse Resource

func (response GetResource200JSONResponse) VisitGetResourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetResource200ApplicationyamlResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response GetResource200ApplicationyamlResponse) VisitGetResourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/yaml")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetResource400JSONResponse Error

func (response GetResource400JSONResponse) VisitGetResourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetResource500JSONResponse Error

func (response GetResource500JSONResponse) VisitGetResourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type RegisterServiceProviderRequestObject struct {
	ResourceType RegisterServiceProviderParamsResourceType `json:"resourceType"`
	Body         *RegisterServiceProviderJSONRequestBody
}

type RegisterServiceProviderResponseObject interface {
	VisitRegisterServiceProviderResponse(w http.ResponseWriter) error
}

type RegisterServiceProvider201JSONResponse ProviderServiceResponse

func (response RegisterServiceProvider201JSONResponse) VisitRegisterServiceProviderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type RegisterServiceProvider400JSONResponse Error

func (response RegisterServiceProvider400JSONResponse) VisitRegisterServiceProviderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type RegisterServiceProvider500JSONResponse Error

func (response RegisterServiceProvider500JSONResponse) VisitRegisterServiceProviderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Health check
	// (GET /health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// Get all resources
	// (GET /resources)
	ListResources(ctx context.Context, request ListResourcesRequestObject) (ListResourcesResponseObject, error)
	// Options for resources
	// (OPTIONS /resources)
	OptionsResources(ctx context.Context, request OptionsResourcesRequestObject) (OptionsResourcesResponseObject, error)
	// Get a resource by type
	// (GET /resources/{resourceType})
	GetResource(ctx context.Context, request GetResourceRequestObject) (GetResourceResponseObject, error)
	// Register a new provider for resource type
	// (POST /resources/{resourceType})
	RegisterServiceProvider(ctx context.Context, request RegisterServiceProviderRequestObject) (RegisterServiceProviderResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListResources operation middleware
func (sh *strictHandler) ListResources(w http.ResponseWriter, r *http.Request) {
	var request ListResourcesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListResources(ctx, request.(ListResourcesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListResources")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListResourcesResponseObject); ok {
		if err := validResponse.VisitListResourcesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// OptionsResources operation middleware
func (sh *strictHandler) OptionsResources(w http.ResponseWriter, r *http.Request) {
	var request OptionsResourcesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.OptionsResources(ctx, request.(OptionsResourcesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "OptionsResources")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(OptionsResourcesResponseObject); ok {
		if err := validResponse.VisitOptionsResourcesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetResource operation middleware
func (sh *strictHandler) GetResource(w http.ResponseWriter, r *http.Request, resourceType GetResourceParamsResourceType) {
	var request GetResourceRequestObject

	request.ResourceType = resourceType

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetResource(ctx, request.(GetResourceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetResource")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetResourceResponseObject); ok {
		if err := validResponse.VisitGetResourceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RegisterServiceProvider operation middleware
func (sh *strictHandler) RegisterServiceProvider(w http.ResponseWriter, r *http.Request, resourceType RegisterServiceProviderParamsResourceType) {
	var request RegisterServiceProviderRequestObject

	request.ResourceType = resourceType

	var body RegisterServiceProviderJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RegisterServiceProvider(ctx, request.(RegisterServiceProviderRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RegisterServiceProvider")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RegisterServiceProviderResponseObject); ok {
		if err := validResponse.VisitRegisterServiceProviderResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
